### PR TITLE
Support normal reddit links in vreddit and minor refactoring

### PR DESCRIPTION
**Pull request by Lonami**

### CODE REVIEW

**Comment by Qwerty-Space** [comment]
image

Nice

From this class:

```python 
class RedditVideoParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.og_video = None

    @classmethod
    async def get_og_video(cls, session, link):
        self = cls()
        async with session.get(m) as resp:
            self.feed(await req.text())
        return self.og_video

    def handle_starttag(self, tag, attrs):
        if tag == 'meta':
            attrs = dict(attrs)
            if attrs.get('property') == 'og:video':
                self.og_video = attrs['content']
```

**Comment by Lonami** [comment]
`m` must be `link` as discussed in private.

**Comment by Qwerty-Space** [comment]
Encountered more errors:

```python
Traceback (most recent call last):
  File "/home/qwerty/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 456, in _dispatch_update
    await callback(event)
  File "/mnt/data/Documents/Documents/Projects/Programming/python/uniborg/botplugins/vreddit.py", line 171, in on_vreddit
    await vreddit(event, links, almost_links)
  File "/mnt/data/Documents/Documents/Projects/Programming/python/uniborg/botplugins/vreddit.py", line 90, in vreddit
    post_json = await resp.json()
  File "/home/qwerty/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/x-mpegurl', url=URL('https://v.redd.it/13xtpqdho7r91/HLSPlaylist.m3u8?a=1667321476,NzhiYzAyNmQyNzMxNTUwYzZkYTA4OWEwZDBiNjExMWY2MmJjZWEyOWI2OGE2YWQ0MDU0YTg1ZGVmNGMzMDBiNg%3D%3D&v=1&f=sd.json')```

I don't have time to debug much more rn.  I might come back to this later.

**Comment by Lonami** [comment]
That's the exact same code `requests` was using https://github.com/Qwerty-Space/uniborg/pull/5/commits/b86fdf1f72217e2cacd1bffe2b23ff5405cc2581.

Unless of course `requests` does something different to `aiohttp`.

**Comment by Lonami** [comment]
I think `requests` would also have failed in that case anyway.

**Pull request merged**
